### ISSUE TITLE
ascii() and wait(WaitMode.Output) function is not working properly

### ISSUE THREAD

**Issue by ravimule93** [3270/j3270#2]
Hi There,

I am using J3270 API for mainframe screen scrapping purpose.
I came across 2 issues:
1. ascii() - which is not working as expected - its not getting the latest screen in the list. 
2.  wait(WaitMode.Output)  - its not waiting for the OUTPUT screen to change.
Can you please help what should be done.

In first case how we can get the latest mainframe screen in the buffer?
What is the better we to check the response screen after pressing the any function keys ?

Thank you in advance! 

You can reach out to me on muleravi2@gmail.com

Thanks,
Ravi

**Comment by dyokomizo** [comment]
Hi Ravi.

j3270 is a wrapper around s3270, so you can try out your sequence of actions using s3270 direcly: all commands available through j3270 are directly translated to the same s3270 commands. I also find s3270 useful to try out things before writing code using j3270.

If the behaviour differs between j3270 and s3270 then it probably is a bug on our end, but in my experience there's always some weird behavior on the mainframe that we're ignoring. For example if "Ascii" works in s3270 but not in j3270 then it's a bug.

Another thing to check is browsing your system using either x3270 (GUI version) or c3270 (terminal version), both use s3270 to do the actual work, so if they don't work then it may be an issue with your mainframe (maybe networking issues).

**Comment by ravimule93** [comment]
Thanks for you response
